apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forum
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: forum
    spec:
      containers:
      - name: forum
        image: jsreport/forum:1.0.0
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /app/public/uploads
          name: general-disk
          subPath: forum/uploads
        ports:
        - containerPort: 4567    
        env:           
        - name: secret
          valueFrom:
            secretKeyRef:
              name: forum
              key: forum.txt
        - name: mongo__host
          value: mongodb
        - name: mongo__username
          value: admin   
        - name: mongo__authDatabase
          value: admin       
        - name: mongo__password
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongo.txt 
      volumes:
        - name: general-disk
          persistentVolumeClaim:
            claimName: general-disk         
---          
apiVersion: v1
kind: Service
metadata:
  name: forum
  labels:
    app: forum
spec:
  selector:
    app: forum
  ports:
    - name: http
      port: 4567          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: forum-ingress
  annotations:    
    kubernetes.io/ingress.class: nginx       
    nginx.ingress.kubernetes.io/limit-rps: "50"           
    ingress.kubernetes.io/force-ssl-redirect: "false"  
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # the default redirect status code is 308 which is not supported in ie on win7    
    nginx.ingress.kubernetes.io/configuration-snippet: |  
      if ($redirect_to_https) {
        return 301 https://$best_http_host$request_uri;				        
      }
spec:
  tls:
  - secretName: forum-tls-secret-full
    hosts:
    - forum.jsreport.net
  rules:  
  - host: forum.jsreport.net
    http:  
      paths:
      - path: /
        backend:
          serviceName: forum
          servicePort: 4567      