apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: general-disk
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi