apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: janblaha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: janblaha
    spec:
      containers:
      - name: janblaha
        image: pofider/janblaha:0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: janblaha
  labels:
    app: janblaha
spec:
  selector:
    app: janblaha
  ports:
    - name: http
      port: 1000        