apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: janblaha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: janblaha
    spec:
      containers:
      - name: janblaha
        image: pofider/janblaha:0.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 1000
        volumeMounts:
        - name: credentials
          mountPath: /app/twitter.keys.json
          subPath: twitter.keys.json
          readOnly: true
        resources:
          limits:
            memory: "64Mi"
            cpu: "0.1"
          requests:
            cpu: "0"
            memory: "0"
      volumes:
      - name: credentials
        secret:
          secretName: janblaha-credentials  
          items:
          - key: janblahaCredentials.json
            path: twitter.keys.json
---
apiVersion: v1
kind: Service
metadata:
  name: janblaha
  labels:
    app: janblaha
spec:
  selector:
    app: janblaha
  ports:
    - name: http
      port: 1000   
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: janblaha-ingress
  annotations:    
    kubernetes.io/ingress.class: nginx   
    ingress.kubernetes.io/ssl-redirect: "false"    
    nginx.ingress.kubernetes.io/limit-rps: "20"       
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = 'janblaha.net' ) {
        rewrite ^ http://www.janblaha.net$request_uri permanent;
      }
spec:
  rules:  
  - host: janblaha.net
    http:  
      paths:
      - path: /
        backend:
          serviceName: janblaha
          servicePort: 1000   
  - host: www.janblaha.net
    http:  
      paths:
      - path: /
        backend:
          serviceName: janblaha
          servicePort: 1000      
             