apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: janblaha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: janblaha
    spec:
      containers:
      - name: janblaha
        image: pofider/janblaha:0.1.12
        imagePullPolicy: Always
        ports:
        - containerPort: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: janblaha
  labels:
    app: janblaha
spec:
  selector:
    app: janblaha
  ports:
    - name: http
      port: 1000   
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: janblaha-ingress
  annotations:    
    kubernetes.io/ingress.class: nginx   
    ingress.kubernetes.io/ssl-redirect: "false"    
    nginx.ingress.kubernetes.io/limit-rps: "10"            
spec:
  rules:  
  - host: janblaha.net
    http:  
      paths:
      - path: /
        backend:
          serviceName: janblaha
          servicePort: 1000                 