apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:  
    metadata:
      labels:
        app: mongodb        
    spec:
      containers:     
      - image: mongo:4.0.0-xenial
        name: mongodb       
        ports:
        - containerPort: 27017      
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data/db
          name: general-disk
          subPath: mongodb/data
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongo.txt
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0"
      volumes:
      - name: general-disk
        persistentVolumeClaim:
          claimName: general-disk
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
  type: LoadBalancer  
  selector:
    app: mongodb      