apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
spec:
  selector:
    matchLabels:
      app: playground
  replicas: 1
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: jsreport/playground:3.5.5
        imagePullPolicy: Always
        ports:
        - containerPort: 5488
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        - mountPath: /memory-dump
          name: memory-dump
        env:
        - name: ip
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: loggly_token
          valueFrom:
            secretKeyRef:
              name: playground
              key: logglyToken
        - name: stack
          value: "prod"
        - name: extensions_dockerWorkers_numberOfWorkers
          value: "3"
        - name: extensions_dockerWorkers_container_memory
          value: "720mb"
        - name: extensions_dockerWorkers_container_memorySwap
          value: "720mb"
        - name: extensions_dockerWorkers_container_cpus
          value: "0.9"
        - name: extensions_dockerWorkers_network
          value: "nw_playground_docker_workers"
        - name: extensions_dockerWorkers_subnet
          value: "182.32.0.0/24"
        - name: extensions_mongodbStore_address
          value: "mongodb"
        - name: extensions_mongodbStore_username
          value: "admin"
        - name: extensions_mongodbStore_password
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongo.txt
        - name: extensions_mongodbStore_authDb
          value: "admin"
        - name: extensions_playground_baseUrl
          value: "https://playground.jsreport.net"
        - name: extensions_mongodbStore_username
          value: "admin"
        - name: extensions_mongodbStore_password
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongo.txt
        - name: extensions_mongodbStore_authDb
          value: "admin"
        - name: extensions_playground_adminUserId
          valueFrom:
            secretKeyRef:
              name: playground
              key: playgroundadmin
        - name: extensions_playground_facebook_clientID
          valueFrom:
            secretKeyRef:
              name: playground
              key: fbid
        - name: extensions_playground_facebook_clientSecret
          valueFrom:
            secretKeyRef:
              name: playground
              key: fbsecret
        - name: extensions_playground_twitter_consumerKey
          valueFrom:
            secretKeyRef:
              name: playground
              key: twkey
        - name: extensions_playground_twitter_consumerSecret
          valueFrom:
            secretKeyRef:
              name: playground
              key: twsecret
        - name: extensions_playground_github_clientID
          valueFrom:
            secretKeyRef:
              name: playground
              key: gtid
        - name: extensions_playground_github_clientSecret
          valueFrom:
            secretKeyRef:
              name: playground
              key: gtsecret
        - name: extensions_authentication_cookieSession_secret
          valueFrom:
            secretKeyRef:
              name: playground
              key: secret
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.6"
          requests:
            cpu: "0"
            memory: "0"
      volumes:
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: memory-dump
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: playground
  labels:
    app: playground
spec:
  selector:
    app: playground
  ports:
    - name: http
      port: 5488
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: playground-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-rps: "50"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # the default redirect status code is 308 which is not supported in ie on win7
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($redirect_to_https) {
        return 301 https://$best_http_host$request_uri;
      }
spec:
  tls:
  - secretName: playground-tls-secret4
    hosts:
    - playground.jsreport.net
  rules:
  - host: playground.jsreport.net
    http:
      paths:
      - path: /
        backend:
          serviceName: playground
          servicePort: 5488
