apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: playground
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: jsreport/playground:2.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 5488
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
        env:      
        - name: ip
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: stack
          value: "test"
        - name: extensions_mongodbStore_username
          value: "admin"            
        - name: extensions_mongodbStore_password
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongo.txt
        - name: extensions_mongodbStore_authDb
          value: "admin"
      volumes:
      - name: docker-sock-volume
        hostPath:        
          path: /var/run/docker.sock         
          type: File
---          
apiVersion: v1
kind: Service
metadata:
  name: playground
  labels:
    app: playground
spec:
  selector:
    app: playground
  ports:
    - name: http
      port: 5488          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: playground-ingress
  annotations:    
    kubernetes.io/ingress.class: nginx   
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/limit-rps: "10"           
spec:
  rules:  
  - host: playground.jsreport.cloud
    http:  
      paths:
      - path: /
        backend:
          serviceName: playground
          servicePort: 5488