apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: support
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: support
    spec:
      containers:
      - name: support
        image: jsreport/forum:1.1.1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /app/public/uploads
          name: general-disk
          subPath: support/uploads
        ports:
        - containerPort: 4567    
        env:           
        - name: secret
          valueFrom:
            secretKeyRef:
              name: support
              key: support.txt
        - name: url
          value: https://support.jsreport.net
        - name: mongo__database
          value: support
        - name: mongo__host
          value: mongodb
        - name: mongo__username
          value: admin   
        - name: mongo__authDatabase
          value: admin       
        - name: mongo__password
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongo.txt 
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.3"
          requests:
            cpu: "0"
            memory: "0"
      volumes:
        - name: general-disk
          persistentVolumeClaim:
            claimName: general-disk         
---          
apiVersion: v1
kind: Service
metadata:
  name: support
  labels:
    app: support
spec:
  selector:
    app: support
  ports:
    - name: http
      port: 4567          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: support-ingress
  annotations:    
    kubernetes.io/ingress.class: nginx       
    nginx.ingress.kubernetes.io/limit-rps: "50"           
    ingress.kubernetes.io/force-ssl-redirect: "false"  
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # the default redirect status code is 308 which is not supported in ie on win7    
    nginx.ingress.kubernetes.io/configuration-snippet: |  
      if ($redirect_to_https) {
        return 301 https://$best_http_host$request_uri;				        
      }
spec:
  tls:
  - secretName: support-tls-secret3
    hosts:
    - support.jsreport.net
  rules:  
  - host: support.jsreport.net
    http:  
      paths:
      - path: /
        backend:
          serviceName: support
          servicePort: 4567      