apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: jsreport/website:0.3.7
        imagePullPolicy: Always
        ports:
        - containerPort: 2000
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
spec:
  selector:
    app: website
  ports:
    - name: http
      port: 2000   
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-ingress
  annotations:    
    kubernetes.io/ingress.class: nginx     
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/limit-rps: "100"            
    ingress.kubernetes.io/force-ssl-redirect: "false"  
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # the default redirect status code is 308 which is not supported in ie on win7    
    nginx.ingress.kubernetes.io/configuration-snippet: |  
      set $shouldRedirect 0;      
            
      if ($redirect_to_https) {
        set $shouldRedirect 1;   
      } 

      # xlsx requires plain http at this moment
      if ($uri ~* \/temp){
        set $shouldRedirect 0;
      }

      if ($shouldRedirect) {         
        return 301 https://jsreport.net$request_uri;			      	        
      } 

      if ($host ~* ^www\.(.*)$) {
        return 301 https://jsreport.net$request_uri;				      
      }  
spec:
  tls:
  - secretName: jsreportnet-tls-secret-full
    hosts:
    - jsreport.net
    - www.jsreport.net
  rules:  
  - host: jsreport.net
    http:  
      paths:
      - path: /
        backend:
          serviceName: website
          servicePort: 2000
  - host: www.jsreport.net
    http:  
      paths:
      - path: /
        backend:
          serviceName: website
          servicePort: 2000                          