apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: jsreport/website:0.1.7
        imagePullPolicy: Always
        ports:
        - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website
spec:
  selector:
    app: website
  ports:
    - name: http
      port: 2000   
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-ingress
  annotations:    
    kubernetes.io/ingress.class: nginx   
    ingress.kubernetes.io/ssl-redirect: "false"    
    nginx.ingress.kubernetes.io/limit-rps: "10"            
spec:
  rules:  
  - host: website.net
    http:  
      paths:
      - path: /
        backend:
          serviceName: website
          servicePort: 2000                 