apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: forum-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: forum-staging
    spec:
      containers:
      - name: forum-staging
        image: jsreport/forum:1.1.1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /app/public/uploads
          name: general-disk
          subPath: forum/uploads
        ports:
        - containerPort: 4567    
        env:           
        - name: secret
          valueFrom:
            secretKeyRef:
              name: forum
              key: forum.txt
        - name: mongo__host
          value: mongodb
        - name: mongo__username
          value: admin   
        - name: mongo__authDatabase
          value: admin       
        - name: mongo__password
          valueFrom:
            secretKeyRef:
              name: mongo
              key: mongo.txt 
      volumes:
        - name: general-disk
          persistentVolumeClaim:
            claimName: general-disk
---   
apiVersion: v1
kind: Service
metadata:
  name: forum-staging
  labels:
    app: forum-staging
spec:
  selector:
    app: forum-staging
  ports:
    - name: http
      port: 4567          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: forum-staging-ingress
  annotations:    
    kubernetes.io/ingress.class: nginx   
    ingress.kubernetes.io/ssl-redirect: "false"    
    nginx.ingress.kubernetes.io/limit-rps: "10"        
    nginx.ingress.kubernetes.io/server-snippet: |
      location /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
      }    
spec:
  rules:  
  - host: forum.jsreport.cloud
    http:  
      paths:
      - path: /
        backend:
          serviceName: forum-staging
          servicePort: 4567      