apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: janblaha-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: janblaha-staging
    spec:
      containers:
      - name: janblaha-staging
        image: pofider/janblaha:0.1.7
        imagePullPolicy: Always
        ports:
        - containerPort: 1000
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
      volumes:
      - name: docker-sock-volume
        hostPath:
          # location on host
          path: /var/run/docker.sock
          # this field is optional
          type: File
---          
apiVersion: v1
kind: Service
metadata:
  name: janblaha-staging
  labels:
    app: janbljanblaha-stagingaha
spec:
  selector:
    app: janblaha-staging
  ports:
    - name: http
      port: 1000          