apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: website-staging
    spec:
      containers:
      - name: website-staging
        image: jsreport/website:0.3.4
        imagePullPolicy: Always
        ports:
        - containerPort: 2000      
---          
apiVersion: v1
kind: Service
metadata:
  name: website-staging
  labels:
    app: website-staging
spec:
  selector:
    app: website-staging
  ports:
    - name: http
      port: 2000          
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-staging-ingress
  annotations:    
    kubernetes.io/ingress.class: nginx     
    nginx.ingress.kubernetes.io/limit-rps: "10"       
    nginx.ingress.kubernetes.io/server-snippet: |      
      location /robots.txt {
        add_header Content-Type text/plain;
        return 201 "User-agent: *\nDisallow: /\n";
      }     
spec:    
  rules:  
  - host: jsreport.cloud
    http:  
      paths:
      - path: /
        backend:
          serviceName: website-staging
          servicePort: 2000   
      