name: main 

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2   

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
    
      - shell: bash   
        env:             
          BRANCH: ${{ steps.extract_branch.outputs.branch }}    
          AZ_APP_ID: ${{ secrets.AZ_APP_ID }} 
          AZ_PASSWORD: ${{ secrets.AZ_PASSWORD }} 
          AZ_TENANT: ${{ secrets.AZ_TENANT }} 
        run: |    
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

          az login --service-principal --username $AZ_APP_ID --password $AZ_PASSWORD --tenant $AZ_TENANT
          az aks install-cli
          az aks get-credentials --resource-group jsreport --name jsreport

          if [ "$BRANCH" == "master" ]; then 
              echo "deploying to production"
              kubectl apply -f ./config/prod
          else    
              SERVICE="$(echo "$BRANCH" | cut -d "-" -f 1)"
              echo "deploying to staging for ${SERVICE}"
              kubectl apply -f ./config/staging/${SERVICE}.yaml
          fi
